github:
  repository: vanja-san/vanja-san.github.io

title: home
description: false
author: vanja-san

baseurl: /
url: vanja-san.github.io
github_username: vanja-san

permalink: pretty
pages_dir: pages
highlighter: rouge

gh-pages:
  branch: gh-pages
  repo: https://github.com/vanja-san/vanja-san.github.io.git
  ignore:
    - assets/stylus

assets:
  stylus:
    enabled: true
    compile: css
    output: assets/css

plugins: [jekyll-paginate, jekyll-feed]
#sass:
#  sass_dir: _sass
#  style: compressed
# Exclude from processing.
# exclude
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
