title: home
description: " "
author: vanja-san

baseurl: "/"
url: vanja-san.github.io
github_username: vanja-san

highlighter: rouge
# theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
