title: Home
description: Home
author: vanja-san

baseurl: /
url: vanja-san.github.io
github_username: vanja-san

permalink: pretty
pages_dir: pages
highlighter: rouge

plugins: []
#sass:
#  sass_dir: _sass
#  style: compressed
# Exclude from processing.
# exclude
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
