name: Jekyll Site

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          gem install bundler --user-install
          export PATH=$PATH:/home/runner/.local/share/gem/ruby/3.0.0/bin
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build
        env:
          JEKYLL_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: $PATH:/home/runner/.local/share/gem/ruby/3.0.0/bin
        run: |
          bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
